# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 23:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_name', models.CharField(max_length=400)),
                ('address', models.CharField(max_length=400, null=True)),
                ('city', models.CharField(max_length=200, null=True)),
                ('state', models.CharField(max_length=200, null=True)),
                ('zip', models.IntegerField(null=True)),
                ('bed_capacity', models.IntegerField(null=True)),
                ('respite_bed', models.IntegerField(default=0, null=True)),
                ('administrator_name', models.CharField(max_length=200, null=True)),
                ('administrator_license_number', models.CharField(max_length=100, null=True)),
                ('doctor_name', models.CharField(max_length=200, null=True)),
                ('doctor_npi', models.IntegerField(null=True)),
                ('operating_cert', models.CharField(max_length=8, null=True)),
                ('facility_npi', models.CharField(max_length=9, null=True)),
                ('tax_id', models.IntegerField(null=True)),
                ('bank_account_number', models.CharField(max_length=30, null=True)),
                ('bank_routing_number', models.CharField(max_length=40, null=True)),
                ('medicaid_number', models.IntegerField(null=True)),
                ('medicare_ptan', models.IntegerField(null=True)),
                ('upin', models.IntegerField(null=True)),
                ('pps_start_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('medicare_m2_id', models.IntegerField(null=True)),
                ('facility_state_assigned_unique_id', models.IntegerField(null=True)),
                ('unique_state_id', models.IntegerField(null=True)),
                ('state_id', models.IntegerField(null=True)),
                ('state_number', models.IntegerField(null=True)),
                ('federal_number', models.IntegerField(null=True)),
                ('status', models.IntegerField(default=1, null=True)),
                ('create_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Residents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('admission_date', models.DateTimeField(verbose_name='date of admission')),
                ('discharge_date', models.DateTimeField(verbose_name='date of discharge')),
                ('payer_source', models.CharField(max_length=200)),
                ('bed_number', models.IntegerField()),
                ('facility_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restrack.Facility')),
            ],
        ),
    ]
