# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restrack', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='facility_type',
            field=models.CharField(choices=[('ADC', 'Adult Day Care'), ('LTHHCP', 'Long Term Home Health Program'), ('NH', 'Nursing Home')], max_length=100, null=True),
        ),
    ]
