# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restrack', '0002_facility_facility_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='facility_type',
            field=models.CharField(choices=[('ADC', 'Adult Day Care'), ('LTHHCP', 'Long Term Home Health Program'), ('NH', 'Nursing Home')], default='Adult Day Care', max_length=100),
            preserve_default=False,
        ),
    ]
