# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 05:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restrack', '0003_auto_20170123_1820'),
    ]

    operations = [
        migrations.RenameField(
            model_name='residents',
            old_name='facility_name',
            new_name='facility_id',
        ),
    ]
